lib/main/atom/atomConfig.ts
lib/main/atom/autoCompleteProvider.ts

add perferred quote settings

---

snippets/typescript-snippets.cson

:art: New _function_ snippet that throws by default

function snippet updated

---

dist/main/atom/typescriptGrammar.js
lib/main/atom/autoCompleteProvider.ts
lib/main/atom/typescriptGrammar.ts
snippets/typescript-snippets.cson
styles/atomts-syntax.less

This pull request fixes issue #363.

Add grammar support for AMD module names and dependency paths

---

dist/main/atom/tooltipManager.js
lib/main/atom/tooltipManager.ts

Fixes tooltip issue

---

grammars/typescript.cson

This is necessary to me. thanks.

feat(grammar): support brace at entity.name.function

---

.gitignore
CONTRIBUTING.md
dist/main/atom/commands/commands.js
dist/main/atom/views/rView.js
dist/main/atom/views/tsconfig.json
dist/main/tsconfig/tsconfig.js
lib/main/atom/commands/commands.ts
lib/main/atom/views/rView.ts
lib/main/tsconfig/tsconfig.ts
lib/tsconfig.json
lib/tsd.json
lib/typings/immutable.d.ts
lib/typings/react/react.d.ts
lib/typings/tsd.d.ts
package.json
styles/atomts-r-view.less

Refs https://github.com/TypeStrong/atom-typescript/issues/318

Feat ReactJS

---

dist/main/lang/fixmyts/quickFixRegistry.js
dist/main/lang/fixmyts/quickFixes/extractVariable.js
lib/main/lang/fixmyts/quickFixRegistry.ts
lib/main/lang/fixmyts/quickFixes/extractVariable.ts
lib/tsconfig.json

This is the first attempt to implement #351

first attempt to implement extract variable

---

grammars/typescript.cson

Fix public/private/protected in front of variables not highlighting properly, as described in #418.

Add storage modifiers to variable in classes.

---

grammars/typescript.cson

It was brought to my attention that a few things were added to TypeScript since I last used it on a larger scale and not all of these work properly right now. Specifically these are tuple types, indexable types and deconstructing in assignments. I'll try and get the things out there ASAP.

[RDY] Further improve grammar.

---

lib/main/lang/fixmyts/quickFixRegistry.ts
lib/main/lang/fixmyts/quickFixes/addClassMethod.ts

Based on the addClassMember.ts, adapted to my needs.

Adds "AddClassMethod" quick fix

---

dist/main/atomts.js
lib/main/atomts.ts
lib/typings/atom/atom.d.ts

Defer plugin activation till after grammar has been initialized

---

lib/main/lang/fixmyts/quickFixes/addClassMethod.ts

Adds anonymous Type/Method/Object and Basic Generics support
Removed /* implement-me */ output comment
Added “Tests” at bottom

Adds anonymous Type/Method/Object and Basic Generics support

---

lib/main/lang/fixmyts/quickFixes/addClassMethod.ts

Fixes array names with "[]" in the argument name.
AddedArray tests at end of addClassMethod.ts

Fixes array names with "[]" in the argument name

---

grammars/typescript.cson

* Fixes issues with types containing `$`signs
* Highlights `implements`

Fix a few issues with the highlighting of types.

---

lib/main/tsconfig/tsconfig.ts

Add support for moduleResolution.

---

dist/main/atom/views/mainPanelView.js
lib/main/atom/views/mainPanelView.ts
styles/atomts-main-panel-view.less

Follow up on #607 to fix a minor padding visual issue (forgot to check with the panel open).
Edit: There's definitely some work to do on smaller screen widths.

Make panel body padding consistent with header

---

lib/linter.ts

Fixes #629
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/typestrong/atom-typescript/631)

Use the new linter name feature

---

dist/main/tsconfig/tsconfig.js
lib/main/tsconfig/tsconfig.ts
lib/tsconfig.json
package.json

Sorry it took a bit to resolve this, I had a few meetings, but thanks for everyone's patience.
Closes #654  and references #651.

Update `tsconfig` with patches

---

dist/main/atom/autoCompleteProvider.js
lib/main/atom/autoCompleteProvider.ts

Avoid autocompletion after semicolon and paren

---

grammars/tsx.cson

fix for https://github.com/TypeStrong/atom-typescript/issues/666

fix for highlighting

---

docs/tsconfig.md

@blakeembrey @basarat A change that I think is important so devs understand `exclude` isn't a fix-all.

Added notes on exclude property.

---

dist/main/tsconfig/tsconfig.js
lib/main/tsconfig/tsconfig.ts
package.json

Keeps the original files and exclude in tact.

Update to latest `tsconfig`

---

docs/packages.md

Should autocomplete be listed if it is in core?

Remove autocomplete from packages list.

---

dist/main/lang/modules/building.js
lib/main/lang/modules/building.ts

I missed this change when merging last time :(

Change babel directory when transforming

---

dist/main/tsconfig/tsconfig.js
lib/main/tsconfig/tsconfig.ts

explicitly add 2 options that come as "silent" defaults
fixes #758

explicitly add compile on save and build on save on generated tsconfig

---

dist/main/tsconfig/tsconfig.js
lib/main/tsconfig/tsconfig.ts

Fixes #762.
Edit: Please bump the version of `ntypescript` to > 20151126.

Add "allowSyntheticDefaultImports" compiler option

---

dist/main/atom/autoCompleteProvider.js
lib/main/atom/autoCompleteProvider.ts

I have added another section to the regex for import auto completes that persists leading white space from the replaced text.

ISSUE-783 Leading white space for import auto complete

---

dist/main/atom/commands/commands.js
lib/main/atom/commands/commands.ts

#655 Fixed off by one error in find all references shortcut: shift+F12

---

README.md

Hi,
I'm creating this pull request to modify the README.md about how to disable CompileOnSave. So you don't need to be asked by different people with a same question like me.
Cheers.

Modify the README about how to disable CompileOnSave

---

package.json

@blakeembrey @nycdotnet @Cu3PO42 (and anyone else)
Think we can push a release through at all with the updated services, running into a few bugs that have been fixed by the latest TS releases.

Updated typescript version, to pickup additions

---

lib/main/tsconfig/tsconfig.ts

adding noImplicitUseStrict support

---

dist/main/tsconfig/tsconfig.js
lib/main/tsconfig/tsconfig.ts

Support allowJs option

---

dist/main/lang/fixmyts/quickFixes/stringConcatToTemplate.js
lib/main/lang/fixmyts/quickFixes/stringConcatToTemplate.ts

Fix a bug in stringConcatToTemplate quick fix

---

dist/main/atomts.js
lib/main/atomts.ts
package.json

This PR upgrades `atom-package-deps` to the latest version
You can see the new Confirmation Dialog in action in [`atom-package-deps` Screenshots](https://github.com/steelbrain/package-deps#screenshots)

Upgrade to latest package-deps

---

snippets/typescript-snippets.cson

Add support for `console.log` snippet

feat(console.log):  snippet

---

README.md

containue -> continue

---

package.json

The current version of TS used doesn't support generic parameter defaults which is causing issues for some folks.

Upgrade typescript to stable 2.3.x

---

npm-shrinkwrap.json

The master branch broke a short time after a successful build due to a dependency being updated. This should prevent that.

Use NPM shrinkwrap
