- lib/main/tsconfig/tsconfig.ts
The TypeScript compiler will look for files with both `.ts` and `.d.ts` extensions when resolving external imports, so atom-typescript also needs to do this.
I didn’t check to see if the existsSync check is really necessary or if this could just be updated to double up the number of files in the map, but I did verify this fixes the problem where you `import foo = require('./foo')` and the file is `foo.d.ts`.
> Fix missing external modules with .d.ts extension

- lib/main/tsconfig/tsconfig.js
- lib/main/tsconfig/tsconfig.ts
Fixes #100.
Resolves the out parameter to be relative to the project.
Previously, it would be relative to the Users profile directory.
> Allow "out" CompilerOption to be relative path to project.

- keymaps/atom-typescript.cson
Keybind for quick fix was not specific enough to override the default core `editor:newline` rule
@basarat
> Make keybinds more specific

- dist/main/lang/core/languageServiceHost2.js
- dist/main/lang/core/project.js
- lib/main/lang/core/languageServiceHost2.ts
- lib/main/lang/core/project.ts
The default lib shouldn't be included when the noLib flag is set. This is the same behavior as the tsc command: https://github.com/Microsoft/TypeScript/blob/master/src/compiler/program.ts#L155
> Don't include the default lib when using the noLib flag

- dist/main/atom/views/mainPanelView.js
- lib/main/atom/views/mainPanelView.ts
I updated the panel heading to disallow text selecting (make it more like a proper app).  You can still select text in the actual error area.  I also made the heading toggle on double-click (same behavior as single-click on the heading-fold button.  Please merge if you think this is cool.
> Error panel UI tweak

- grammars/typescript.cson
> End variable declarations on of keyword for ES6 loops. Fixes #451.

- lib/main/atom/commands/commands.ts
- lib/main/atom/commands/json2dtsCommands.ts
- lib/main/json2dts/json2dts.ts
- package.json
This adds support to generate Interface Declaration from JSON like data.
Basically is a port from [json2dts](http://xperiments.in/json2dts/) and old project...
I have tried to "clone" the same code and logic found in the HTMLtoJSX, but I am not sure that populating the "main" directory with command dependencies is a good idea.
> Adds support to generate Interface Declaration from JSON like data

- CONTRIBUTING.md
- dist/main/atom/views/mainPanelView.js
- lib/main/atom/views/mainPanelView.ts
These are some fixes for:
* the documentation for how to get debugging working when hacking on atom-typescript.
* an occasional error thrown in mainPanelView if the panelView is undefined for some reason.  (Note I couldn't help myself and did some fixing of the code with curly braces, etc.)
> Small fixes

- settings/language-typescript.cson
I have found out that the grammar relies on [`#comments`](https://github.com/TypeStrong/atom-typescript/blob/master/grammars/typescript.cson#L1292), which is in fact copied from [javascript grammar](https://github.com/atom/language-javascript/blob/master/grammars/javascript.cson). 
Adding settings (copied from javascript grammar) ensures that the `commentStartString` is set to `// `.
The grammar options taken from javascript grammar, such as `#comments` I referred to earlier, might not even be necessary, since they are already provided from js grammar, but this has to be investigated and tested further, it should be done in separate PR.
> :bug: fix comment string as pointed out in #507

- lib/main/lang/modules/building.ts
- lib/main/tsconfig/tsconfig.ts
Hello. I am developing https://github.com/s-panferov/awesome-typescript-loader and I decided to implement a feature to pick-up precompiled files for `.ts` modules if any. I need this to speed-up TypeScript + Babel use-case, because this pair is really slow on a big codebases. Unfortunately, `atom-typescript` `externalTranspiler` functionality has several issues:
1. There is no way to pass options into Babel.
2. There is no way  to use `.babelrc` file, because `filename` property is not passed into babel options and babel doesn't know where to look for the `.babelrc` file.
3. Generated source maps are possibly incorrect, because I get an error while using them in my workflow: 
```
RROR in ../arui/src/icon/common/icon.tsx
Module build failed: Error: No element indexed by 1
at ArraySet_at …
```
> Improve babel integration

- dist/main/atom/views/simpleOverlaySelectionView.js
- lib/main/atom/views/simpleOverlaySelectionView.ts
This fixes the issue mentioned in https://github.com/TypeStrong/atom-typescript/issues/542. When the SimpleOverlaySelectListView is called after the first initialization, only the options are set on the singleton but not the editor. This leads to the overlay opening in the previous editor when triggered from a second editor. 
This is simply fixed by setting the editor, too, when the singleton already exists. I tested this out for a while and seems to work fine.
> Fix Quick Fix overlay issue when toggled on a second file

- dist/main/atom/views/mainPanelView.js
- lib/main/atom/views/mainPanelView.ts
Fixes issue #524
Hope it looks okay. I'm pulling the compileOnSave directly from the cache.
> Hide fileStatus when compileOnSave is false

- CONTRIBUTING.md
- lib/main/atom/commands/commands.ts
- lib/main/atomts.ts
- package.json
It has a method `install` that handles the notification and all for you. It resolves the promise when all deps are installed and enabled/activated.
Some of the linter providers are using it already, others will do it very soon.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/typestrong/atom-typescript/559)
> Use atom-package-deps

- dist/main/atom/autoCompleteProvider.js
- lib/main/atom/autoCompleteProvider.ts
By trimming the replacement prefix before handing it back to autocomplete-plus the whitespace in the user code is preserved when activating a suggestion.
Fixes #525
> Conserves padding during autocomple in JSX

- dist/main/atom/views/mainPanelView.js
- lib/main/atom/views/mainPanelView.ts
Status bar will corrupt/wrap with some themes and zoom levels, this fixes that
JS compilation text is more consistent with the other status text and easier to read as it is shorter
> Fixed bad format for some themes & status now easier to read

- dist/main/atom/views/mainPanelView.js
- lib/main/atom/views/mainPanelView.ts
Mostly making use of flex box instead of display hacks, but also made a change for the buttons to overlay the slightly larger panel resize drag area.
Edit: Moved the `showPending` to the parent element so people can click on the number (oddly, the theme I'm using doesn't even have a loading icon yet).
Closes #606
> Tidy up the CSS for the bottom panel

- dist/main/tsconfig/tsconfig.js
- lib/main/tsconfig/tsconfig.ts
Aimed at closing https://github.com/TypeStrong/atom-typescript/issues/377. However, please note that contrary to https://github.com/Microsoft/TypeScript/pull/3188, this support globs. Also, this seems to be too simple... It does solve our usecase (excluding node_modules, same issue as https://github.com/TypeStrong/atom-typescript/issues/332).
> Add support for exclude in tsconfig.

- dist/main/atom/views/mainPanelView.js
- lib/main/atom/views/mainPanelView.ts
By removing the fadeOut we also remove the css rule ```display: none;```. This way the bottom bar doesn't jump on a specific width.
> "Jumpy" Bottom Bar - fadeOut/fadeIn replaced by animate

- grammars/tsx.cson
Hello @basarat! Yesterday i fixed [#666](https://github.com/TypeStrong/atom-typescript/issues/666), but it breaks
this grammar supports typescript (shameless copy [from  sublime-typescript](https://github.com/Microsoft/TypeScript-Sublime-Plugin/blob/master/TypeScriptReact.YAML-tmLanguage) it's better then babel grammar because for typescript :)
Please, check
> updated grammar for tsx

- lib/worker/lib/workerLib.ts
Hello,
Working on NixOS, it is extremely bad that atom-typescript overwrites the environment of the process when calling spawn.
In particular, the child process fails to spawn as it cannot find libgtk-x11.
This patch attempts to solve this issue by only overriding the existing environment.
What is the policy with regards to pull requests? I notice the dist/ repository is tracked, which is weird, but I guess it's useful for bootstrapping?
Best regards,
> workerLib's spawn should preserve the environment

- dist/main/atom/tooltipManager.js
Issue #647 mentions the problem.
> Fixes issue with getScrollTop and getScrollLeft in Atom 1.1.0

- lib/main/atom/views/mainPanelView.ts
Ref https://github.com/TypeStrong/atom-typescript/issues/681 and in general fix for problem when atom is opening around 20-30 tabs when you click on the error message (in TS panel only).
> Fix for duplicate events in the error panel

- dist/main/tsconfig/tsconfig.js
- lib/main/tsconfig/tsconfig.ts
Per options added in Microsoft/TypeScript#4788.
This fixes #720
> Support new tsconfig options for reachability checks

- dist/main/tsconfig/tsconfig.js
- docs/faq.md
- docs/tsconfig.md
- lib/main/tsconfig/tsconfig.ts
The rewriteTsconfig flag enables users to prevent Atom-Typescript
from rewriting their tsconfig.json. The flag defaults to true,
so users who upgrade won't observe any different behavior.
The FAQ and tsconfig docs have been modified to reflect
rewriteTsconfig.
This resolves #703.
> Support rewriteTsconfig flag in tsconfig.json

- dist/main/lang/modules/building.js
- lib/main/lang/modules/building.ts
- package.json
This removes the dependency on `atom-typescript`'s local copy of babel, and allows a given project to use whatever version they like (assuming the core  `.transform` api doesn't change anyway).
Also adds support for loading configuration from `.babelrc`
> Added support for running the local copy of babel for a given project

- dist/main/lang/modules/building.js
- lib/main/lang/modules/building.ts
Conditional to proceed or not after seeking .babelrc was not
couched in else nor returning, and therefore was both resolve(babel)ing as well
as going and trying to read the non-existent file.
Don't try to read the non-existent file.
Closes #742
> don't try to read missing .babelrc file

- dist/main/lang/modules/building.js
- dist/main/lang/projectService.js
- lib/main/lang/modules/building.ts
- lib/main/lang/projectService.ts
Create new function `getRawOutputPostExternal` with same interface
as getRawOutput except that it returns a `<Promise<ts.EmitOutput>`
instead of a ts.EmitOutput.
This function calls getRawOutut, then passes the result through
`runExternalTranspiler` so that babel, if configured, is applied.
Call/use this new function in `getOutputJsStatus`.
Net result: people using babel are not constantly being told their
JS is Outdated.
> use externalTranspiler before doing diffs for status

- dist/main/lang/fixmyts/quickFixRegistry.js
- dist/main/lang/fixmyts/quickFixes/addImportFromStatement.js
- lib/main/lang/fixmyts/quickFixRegistry.ts
- lib/main/lang/fixmyts/quickFixes/addImportFromStatement.ts
- lib/tsconfig.json
Provides a new quick fix option for creating an `import {Foo} from "./deep/folder/path/foo"` statement.
> add new quick fix class for import from

- grammars/typescript.cson
Added simple support for Angular2 inline template highlighting. In short, if we find something that looks like this:
@Component({
template: `
<some><html><here></here></html></some>
`
})
We activate text.html.basic highlighting on the contents of the multiline string.
It's possible that we could look specifically for @Component, but right now, we're piggybacking off of #decorator to prevent weirdness/code duplication.
To make this work, I had to remove the $base include from #decorator. If people begin passing anonymous functions and so on to decorators, this will need revisiting. But right now, we're talking about booleans and objects, so I don't know that it really needs $base. If it does, probably better to just catch @Component->template on its own.
> Angular2 Decorator Template Highlighting

- README.md
- dist/main/atom/onSaveHandler.js
- dist/main/tsconfig/tsconfig.js
- docs/tsconfig.md
- lib/main/atom/onSaveHandler.ts
- lib/main/tsconfig/tsconfig.ts
- lib/tsconfig.json
#810 
I wasn't sure if this should be a default on, so I decided to have it defaulted to off.
> Auto format on save

- docs/tsconfig.md
Here is a little fix for the tsconfig.md documentation.
You mention a 'gs' snippet but the example in tsconfig.md differs from the snippet.
Is does not just differ but it seems to have a bug. I tried it and
the ./ prefix does not work for me - so I removed it for you.
Also the generated files section has no ./ prefix.
> Fix tsconfig.md regarding ./ prefix

- dist/main/tsconfig/tsconfig.js
- lib/main/tsconfig/tsconfig.ts
- package.json
Added support for target: es2015 in `tsconfig.json`. Support for this in TypeScript can be found [here](https://github.com/Microsoft/TypeScript/blob/0f67f4b6f1589756906782f1ac02e6931e1cff13/src/compiler/commandLineParser.ts#L232) and [here](https://github.com/Microsoft/TypeScript/blob/e2c95551b348b10bed7d42fdaff857143e631a0d/src/compiler/diagnosticMessages.json#L2355). (The second example rather suggests that `es2015` is going to replace `es6` in the future.)
I didn't notice any tests associated with this - do point me in the right direction if I've missed them.
> Added support for a target of es2015

- dist/main/tsconfig/tsconfig.js
- lib/globals.ts
- lib/main/tsconfig/tsconfig.ts
- package.json
I fixed #678 to be able to save tsconfig.json with LF in Windows.
Used https://github.com/sindresorhus/detect-newline because there are already used detect-indent.
> tsconfig.json is saved with the same new line characters as the previous one

- grammars/ts.cson
- grammars/tsx.cson
- scripts/grammar.js
I noticed that strings were no longer being colored correctly.  This may have been due to a recent change where the styles of Atom now include quoted in the name.
I figured this out by comparing the styles between atom-typescript and the other language syntax plugins.
> Fix String Highlighting

- dist/main/lang/core/languageServiceHost2.js
- dist/main/tsconfig/tsconfig.js
- lib/main/lang/core/languageServiceHost2.ts
- lib/main/tsconfig/tsconfig.ts
Since `ntypescript` still using `ts.getNewLineOrDefaultFromHost()` to
get new line character, we need provide `getNewLine` function in
`LanguageServiceHost`. Fix #545
> fix #545, respect compiler option `newLine`

- dist/main/tsconfig/tsconfig.js
- lib/main/tsconfig/tsconfig.ts
This option should be suppored by the latest typescript compiler:
https://www.typescriptlang.org/docs/handbook/compiler-options.html
> Add support for validating the "skipDefaultLibCheck" for compiler options

- dist/main/tsconfig/tsconfig.js
- lib/main/tsconfig/tsconfig.ts
Adds support for tsconfig's `strictNullChecks` option added in https://github.com/Microsoft/TypeScript/pull/7140.
> Allow tsconfig strictNullChecks option

- dist/main/lang/fixmyts/quickFixes/stringConcatToTemplate.js
- lib/main/lang/fixmyts/quickFixes/stringConcatToTemplate.ts
I experienced an error building my pull-request: https://github.com/TypeStrong/atom-typescript/pull/948
First I that the error my relates to my changes but this is not the case.
The problem is located in `quickfixes/stringConcatToTemplate.ts`.
There was a function declaration within a while-loop causing `$ npm test` to throw an error.
I moved the concerned method (appendToFinal) into a private method.
Please have a look to my changes.
Kinds
Greg
> Fixing Travis CI Build

- dist/main/lang/core/languageServiceHost2.js
- dist/main/lang/typescriptServices.js
- dist/worker/child.js
- lib/main/lang/core/languageServiceHost2.ts
- lib/main/lang/typescriptServices.ts
- lib/tsconfig.json
- lib/worker/child.ts
This is a fix for #923, to load default lib from custom `typescriptServices` path.
> Load lib.d.ts from typescriptServices path

- dist/main/atom/commands/commands.js
- dist/main/atom/views/typeOverlayView.js
- lib/main/atom/commands/commands.ts
- lib/main/atom/views/typeOverlayView.ts
- lib/tsconfig.json
- styles/atomts-show-type-view.less
This PR adds a `show-type` command that displays type information at the cursor. The overlay looks like this:
Some notes:
* The type information overlay is dismissed when the cursor position changes, the escape key is pressed, or when the editor the overlay is in loses focus.
* I did not merge this code path with the one that displays type information on hover, mostly out of laziness.
* This is my first change on an Atom package so any improvement suggestions would be very welcome.
> #726 adds show-type command for type info at cursor

- lib/hyperclickProvider.ts
- lib/main/atomts.ts
- lib/tsconfig.json
- package.json
Hi 
I see #448 talk about this.​ Any suggestions are welcome.
> Implement go to declaration with hyperclick provider

- dist/hyperclickProvider.js
- lib/hyperclickProvider.ts
hyperclick not underline variable that has underscore case. see the picture below
> Fixed bug hyperclick not cover variable or method that have underscore

- dist/main/tsconfig/tsconfig.js
- lib/main/tsconfig/tsconfig.ts
This adds support for `noImplicitThis` and `noUnusedLocals` tsconfig options.
> Add a couple tsconfig options to atom-typescript

- dist/main/tsconfig/tsconfig.js
- lib/main/tsconfig/tsconfig.ts
[x] All compiled assets are included (atom packages are git tags and hence the built files need to be a part of the source control)
Definition in commandLineParser.ts:
https://github.com/Microsoft/TypeScript/blob/f19844fbe97656a9e1f743fb6fe4e9d706a83c0d/src/compiler/commandLineParser.ts#L349
> Support the "types" compiler option in tsconfig.json.

- dist/main/tsconfig/tsconfig.js
- lib/main/tsconfig/tsconfig.ts
> Support TS 2.0 flag noUnusedParameters

- dist/main/tsconfig/tsconfig.js
- lib/main/tsconfig/tsconfig.ts
[x] All compiled assets are included (atom packages are git tags and hence the built files need to be a part of the source control)
This pull request adds `typeRoots` compiler option in tsconfig. http://json.schemastore.org/tsconfig
> Support tsconfig "typeRoots" compiler option

- dist/hyperclickProvider.js
- lib/hyperclickProvider.ts
[x] All compiled assets are included (atom packages are git tags and hence the built files need to be a part of the source control)
Fixes #1062 
Fixes https://github.com/AsaAyers/js-hyperclick/issues/30
Refs https://github.com/AsaAyers/js-hyperclick/issues/31
> Prevent returning suggestions for files that aren't TypeScript

- dist/main/tsconfig/tsconfig.js
- lib/main/tsconfig/tsconfig.ts
This commit adds support for the new `importHelpers` flag (see [here](https://github.com/Microsoft/TypeScript/pull/9097)).
Interestingly when I ran `npm run build` it changed the 2 grammar files quite heavily, but I didn't include that in this commit/PR.
> Support for tsconfig "importHelpers"

- dist/main/tsconfig/tsconfig.js
- lib/main/tsconfig/tsconfig.ts
Fixes #1085 
Closes #1081 
Fixes #1046
> Add skipLibCheck and declarationDir tsconfig options

- dist/main/atom/commands/outputFileCommands.js
- dist/worker/lib/workerLib.js
- lib/main/atom/commands/outputFileCommands.ts
- lib/worker/lib/workerLib.ts
This PR fixes #1098 and adds support for Atom 1.12+. It'd be cool if you guys could release an update ASAP for the other beta testers. 🙂
It was caused by the removal of `ATOM_SHELL_INTERNAL_RUN_AS_NODE` from electron, which in turn has long been renamed to `ELECTRON_RUN_AS_NODE`.
P.S.:
> When I hit this really really annoying bug, it already seemed like something didn't run the `child.js` in a node process like it was supposed to, but instead tried to open or evaluate it which probably caused the file to open with the default file handler (at least that's what I thought). Searching for `child.js` and anything that launches or opens files lead me to `workerLib.ts` and the only `spawn()` in there with it's very suspicious env var. 😂 Best bugfix ever. 10/10 for being much easier than I …
> Fixed usage of deprecated electron env vars

- styles/atom-typescript-tooltip.less
this should fix #919 
after this fix, tooltips should display like so:
> fix: tooltip contents floats out of the tooltip container

- dist/main/atom/autoCompleteProvider.js
- lib/main/atom/autoCompleteProvider.ts
Resolves #1033 'Overly eager autocomplete after typing some characters'. 
I investigated whether it would be possible to only give autocomplete if the user types a character that is valid to start a variable name, but it turns out that's [quite complicated](http://stackoverflow.com/a/9337047/284741), particularly given that Javascript's regex engine does not have any inbuilt definitions of the relevant unicode groups. The quick fix I've added removes 90% of the irritation for me.
> Autocomplete does not suggestion options after typing '{'

- .travis.yml
- CONTRIBUTING.md
- dist/main/lang/core/languageServiceHost2.js
- dist/main/tsconfig/tsconfig.js
- dist/typescript/makeTypeScriptGlobal.js
- docs/faq.md
- lib/globals.ts
- lib/main/lang/core/languageServiceHost2.ts
- lib/main/tsconfig/tsconfig.ts
- lib/tsconfig.json
- lib/typescript/makeTypeScriptGlobal.ts
- package.json
This PR removes `ntypescript` as a dependency and instead uses `byots` (https://github.com/basarat/byots) to get Typescript's internal types as well as the official nightly Typescript package. This should help keep us up to date with the compiler. It's also step in the direction of potentially using the same Typescript package from the project that you're working on.
> Update typescript, use byots and remove all references to ntypescript

- dist/typescript/makeTypeScriptGlobal.js
- lib/typescript/makeTypeScriptGlobal.ts
Code run with `vm.runInContext` is not wrapped with the helper that sets `__dirname` and `__filename` variables so it was throwing an error. A simple require is all that's needed in this case.
> Fix the custom path to typescriptServices.js feature

- dist/main/atom/commands/commands.js
- dist/main/atom/components/ts-view.js
- lib/main/atom/commands/commands.ts
- lib/main/atom/components/ts-view.ts
Fixes an issue with "Find references" view (perhaps others too) where some Typescript fragments would not be displayed correctly due to an escaping issue. This was especially painful when searching `.tsx` uses.
Before:
After:
> Fix escaping of the results in reference view

- dist/main/atom/autoCompleteProvider.js
- lib/main/atom/autoCompleteProvider.ts
Fixes #1122
Fixes #1111
The scopes `atom-typescript` expected didn't match after updating the grammar. There are a few more places where the `es6import.path.string` scope is used so some stuff is still going to be broken.
Cleaned up some of the suggestion insertion logic to make sure whatever the user has already entered gets replaced and undo works as expected.
> Update module completion with the new scopes

- snippets/typescript-snippets.cson
Add snippet to import using single quotes (as in Angular2, angular-cli, etc) as `importq`, additional to `import`.
I see this has been debated here https://github.com/TypeStrong/atom-typescript/issues/203 and here https://github.com/TypeStrong/atom-typescript/issues/259.
Right now the checks run OK, but the snippet generates imports with only double quote characters.
Using the `import` snippet generates an import statement with double quote characters (`"`), and if the preferred quote character was `'` it complains that they should be single quote characters. But currently there is no snippet to generate imports with single quote characters from the beginning.
I think this additional snippet might help keep happy both sides (single and double quote "sides").
---
> All compiled assets are …
> Add snippet to import using single quotes (as in Angular2)

- dist/main/tsconfig/tsconfig.js
- lib/main/tsconfig/tsconfig.ts
Very minimal change but makes the definition follow the handbook.
https://www.typescriptlang.org/docs/handbook/compiler-options.html
Closes #960.
> As per the typescript handbook, allow "none" as a valid module.

- package.json
TypeScript 2.1 is now [officially released](https://blogs.msdn.microsoft.com/typescript/2016/12/07/announcing-typescript-2-1/) – this PR updates `atom-typescript` to use v2.1, allowing object spread syntax etc.
> Update TypeScript to v2.1

- styles/atomts-grammar-syntax.less
I had to open yet another PR for this because the scopes that the stylesheet was highlighting haven't worked for some time now since their names kept changing with updates to the grammar. No one had noticed so maybe it's not that important, but I updated them anyway.
Thanks to everyone who contributed issues and PRs.
Closes #1183, closes #1175, closes #1167, closes #1108, closes #1168.
> Update grammar styles

- styles/highlights.less
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
atom-text-editor::shadow .highlights .atom-typescript-occurrence .region => atom-text-editor.editor .highlights .atom-typescript-occurrence .region
Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.
[ ] All compiled assets are included (atom packages are git tags and hence the built files need to be a part of the source …
> [fix error] Deprecated selector

- dist/main/atom/editorSetup.js
- lib/main/atom/editorSetup.ts
Fix #1199 by adding the `typescript-editor` class to the editor where `typescript` is activated and removing this class when the editor is destroyed.
[x] All compiled assets are included (atom packages are git tags and hence the built files need to be a part of the source control)
> Add/remove 'typescript-editor' class from <atom-text-editor> elements where typescript is active

- lib/main/atom/tooltipManager.ts
fix -> https://github.com/TypeStrong/atom-typescript/issues/1150
> [fix #1150] deprecated error

- lib/main/atom/tooltipManager.ts
Arguments to path.basename must be strings
> [fix #1171] Object.basename is deprecated

- lib/main/lang/projectService.ts
See https://github.com/TypeStrong/atom-typescript/issues/1191.
This PR makes quickfix to fall back to the closest error in the current file in case no error is on the position of the cursor.
> quickfix to fall back to closest error in the file

- dist/main/atom/commands/goToDeclaration.js
- keymaps/atom-typescript.cson
- lib/main/atom/commands/goToDeclaration.ts
- menus/atomts-menus.cson
> add return-to-declaration functionality on the tsserver branch

- CONTRIBUTING.md
The contribution guide didn't cover all the details for me to get started on a fork. I think that the atom CLI interface and shortcuts changed a bit in the meantime. (e.g. the apm links that are stored in a `dev` node_modules folder, and the `--dev` flag to start atom in debug mode)
> updated contribution guide

- dist/main/atomts.js
- dist/main/errorPusher.js
- lib/main/atomts.ts
- lib/main/errorPusher.ts
- lib/typings/atom_core.d.ts
I had some issues due to TS and atom-TS treating everything with severity `Error`. 
Particularly situations where you'd like to be notified of the occasional unused variable / parameter, but where you don't want these notifications to clutter your interface that much that you'll miss the more severe TS errors.
Things in this PR are:
- Added an atom-typescript option that shows unused values with severity `info` (defaults to `true`)
- Modified the `errorPusher` file to check the error message, and switch to severity `info` when the above option is set.
Particularly the last item might need some discussion: I'm simply applying a string-match that checks for substring ` is declared but never used`. Ideally I'd like to be able to use TS error codes or something, but afaik the only information …
> Support showing 'unused' ts errors with severity 'info'

- README.md
- keymaps/atom-typescript.cson
remove `typescript:quick-fix` from keymap, it does nothing and conflict `intentions:show`, resulting in codefixes unusable on linux or windows without editing keymap.
also document codefixes in readme
> Remove conflicting typescript:quick-fix from keymap

- README.md
The link pointed to a non-existent file in a different location,
I presume that it was simply outdated.
> Correct link to change log

- README.md
- dist/client/client.js
- dist/client/clientResolver.js
- dist/main/pluginManager.js
- docs/faq.md
- lib/client/client.ts
- lib/client/clientResolver.ts
- lib/main/pluginManager.ts
- spec/package.spec.ts
“Typescript” → “TypeScript”. All compiled assets are included.
> Fix spelling of “TypeScript”

- package.json
Change "signagure" to "signature"
> Fix typo in "TypeScript locale" settings

- README.md
- docs/faq.md
- docs/packages.md
- When explaining how the config options specific to projects work, it got confusing when you got to the example, so I edited the text so it would be easier to understand.
- Made explanatory text under last-cursor-position more understandable and more pleasant to read.
- Added link to “failed to update” so that if the user doesn’t read the entire thing but is instead scrolling through the faqs, they know what to click to get to the correct instructions.
Unify #1516 #1517 and #1518 for cleaner commit history + minor formatting tweaks
> Grammar and wording fixes in docs
